sonar.projectKey=Dennis-2003_AcademicScopeBackend
sonar.organization=Dennis-2003
sonar.projectName=AcademicScope Backend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/dto/**,**/model/**,**/enums/**,**/auth/dto/**,**/auth/filter/**,**/config/**,**/DataInitializer.*
